run-1:
    gleam run --target javascript 2 inputs/input.txt
test-1:
    test `gleam run --target javascript 2 ./inputs/test.txt` == 11
run-2:
    gleam run --target javascript 2 inputs/input.txt
test-2:
    test `gleam run --target javascript 2 ./inputs/test.txt` == 31
