compile:
    gcc main.c

run-1: compile
    ./a.out part1 inputs/input.txt
run-2: compile
    ./a.out part2 inputs/input.txt

test: compile test-1 test-2
test-1: compile
    #!/usr/bin/env bash
    test `./a.out part1 inputs/test.txt` == 11
test-2: compile
    #!/usr/bin/env bash
    test `./a.out part2 inputs/test.txt` == 31
