compile:
    gcc main.c

run-1: compile
    ./a.out part1 inputs/input.txt
run-2: compile
    ./a.out part2 inputs/input.txt

test: test compile test-1 test-2
test-test:
    test 1 == 1
test-1: compile
    echo "`./a.out part1 inputs/test.txt`"
    test `./a.out part1 inputs/test.txt` == 11
test-2: compile
    test `./a.out part2 inputs/test.txt` == 31
