run-1:
    mix run src/main.exs part1 inputs/input.txt
run-2:
    # NOTE: it takes around 30s
    # >> reduced to ~10s with task.async
    mix run src/main.exs part2 inputs/input.txt
test:
    mix test
