build:
    @clang++ main.cpp
run-1: build
    @./a.out 1 inputs/input.txt
run-2: build
    @./a.out 2 inputs/input.txt
test: test-1 test-2
test-1: build
    test `./a.out 1 inputs/test.txt` == 18
test-2: build
    test `./a.out 2 inputs/test.txt` == 9
