run-1:
    stack run 1 inputs/input.txt
run-2:
    stack run 2 inputs/input.txt
test: test-1 test-2
test-1:
    #!/usr/bin/env bash
    set -euxo pipefail
    test `stack run 1 inputs/test.txt` == 2
test-2:
    #!/usr/bin/env bash
    set -euxo pipefail
    test `stack run 2 inputs/test.txt` == 4

format:
    ormolu --mode inplace $(find . -name '*.hs')
