name: test

on:
  push:
    branches:
      - master
      - main
  pull_request:

jobs:
  day1:
    name: "Test Day 1"
    runs-on: ubuntu-latest
    defaults: { run: { working-directory: day1 } }
    steps:
      - uses: actions/checkout@v4
      - uses: erlef/setup-beam@v1
        with:
          otp-version: "27.1.2"
          gleam-version: "1.6.2"
          rebar3-version: "3"
      - run: gleam deps download
      - run: gleam test
      - run: gleam format --check src test
