name: "Test"

on:
  push:
    branches:
      - master
      - main
  pull_request:

defaults:
  run:
    shell: bash

jobs:
  # FIXME: "test" builtin cmd doesn't work on GitHub Actions, so use a testing lib for each language
  # untested: day1(C), day2(Haskell), day4(C++)
  # - uses: extractions/setup-just@v2
  # - run: just test
  day1:
    name: "Day 1"
    runs-on: ubuntu-latest
    defaults: { run: { working-directory: day1 } }
    steps:
      - uses: actions/checkout@v4
      - uses: extractions/setup-just@v2
      - run: just test
  day2:
    name: "Day 2"
    runs-on: ubuntu-latest
    defaults: { run: { working-directory: day2 } }
    steps:
      - uses: actions/checkout@v4
      - uses: haskell-actions/setup@v2
      - uses: extractions/setup-just@v2
      - uses: haskell-actions/run-ormolu@v14
  day3:
    name: "Day 3"
    runs-on: ubuntu-latest
    defaults: { run: { working-directory: day3 } }
    steps:
      - uses: actions/checkout@v4
      - uses: oven-sh/setup-bun@v2
      - run: bun test
      - uses: biomejs/setup-biome@v2
      - run: biome check .
  day5:
    name: "Day 5"
    runs-on: ubuntu-latest
    defaults: { run: { working-directory: day5 } }
    steps:
      - uses: actions/checkout@v4
      - uses: extractions/setup-just@v2
      - uses: erlef/setup-beam@v1
        with:
          otp-version: "27.1.2"
          gleam-version: "1.6.2"
          rebar3-version: "3"
      - run: just test
  day6:
    name: "Day 6"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version: "1.23"
      - run: go test ./...
        working-directory: day6
    
