name: "Test"

on:
  push:
    branches:
      - master
      - main
  pull_request:

defaults:
  run:
    shell: bash

jobs:
  day1:
    name: "Day 1"
    runs-on: ubuntu-latest
    defaults: { run: { working-directory: day1 } }
    steps:
      - uses: actions/checkout@v4
      - uses: extractions/setup-just@v2
      - run: just test
  day2:
    name: "Day 2"
    runs-on: ubuntu-latest
    defaults: { run: { working-directory: day2 } }
    steps:
      - uses: actions/checkout@v4
      - uses: extractions/setup-just@v2
      - uses: dorny/paths-filter@v3
        with:
          filters: |
            day2:
              - 'day2/**'
      - uses: haskell-actions/setup@v2
        if: steps.changes.outputs.day2 == 'true'
      - uses: haskell-actions/run-ormolu@v14
        if: steps.changes.outputs.day2 == 'true'
      - run: just test
        if: steps.changes.outputs.day2 == 'true'
  day3:
    name: "Day 3"
    runs-on: ubuntu-latest
    defaults: { run: { working-directory: day3 } }
    steps:
      - uses: actions/checkout@v4
      - uses: oven-sh/setup-bun@v2
      - run: bun test
      - uses: biomejs/setup-biome@v2
      - run: biome check .
  day4:
    name: "Day 4"
    runs-on: ubuntu-latest
    defaults: { run: { working-directory: day4 } }
    steps:
      - uses: actions/checkout@v4
      - uses: extractions/setup-just@v2
      - run: just test
  day5:
    name: "Day 5"
    runs-on: ubuntu-latest
    defaults: { run: { working-directory: day5 } }
    steps:
      - uses: actions/checkout@v4
      - uses: extractions/setup-just@v2
      - uses: erlef/setup-beam@v1
        with:
          otp-version: "27.1.2"
          gleam-version: "1.6.2"
          rebar3-version: "3"
      - run: just test
  day6:
    name: "Day 6"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version: "1.23"
          cache-dependency-path: day6/go.sum
      - run: go test ./...
        working-directory: day6
  day7:
    name: "Day 7"
    runs-on: ubuntu-latest
    defaults: { run: { working-directory: day7 } }
    steps:
      - uses: actions/checkout@v4
      - uses: erlef/setup-beam@v1
        with:
          otp-version: "27.1.2"
          elixir-version: "1.17.3"
          rebar3-version: "3"
      - run: mix test  
