name: "Test"

on:
  push:
    branches:
      - master
      - main
  pull_request:

defaults:
  run:
    shell: bash

jobs:
  day-01:
    name: "Day 1"
    runs-on: ubuntu-latest
    defaults: { run: { working-directory: day-01 } }
    steps:
      - uses: actions/checkout@v4
      - uses: extractions/setup-just@v2
      - run: just test
  day-02:
    name: "Day 2"
    runs-on: ubuntu-latest
    defaults: { run: { working-directory: day-02 } }
    steps:
      - uses: actions/checkout@v4
      - uses: extractions/setup-just@v2
      - uses: dorny/paths-filter@v3
        with:
          filters: |
            day-02:
              - 'day-02/**'
      - uses: haskell-actions/setup@v2
        if: steps.changes.outputs.day-02 == 'true'
      - uses: haskell-actions/run-ormolu@v14
        if: steps.changes.outputs.day-02 == 'true'
      - run: just test
        if: steps.changes.outputs.day-02 == 'true'
  day-03:
    name: "Day 3"
    runs-on: ubuntu-latest
    defaults: { run: { working-directory: day-03 } }
    steps:
      - uses: actions/checkout@v4
      - uses: oven-sh/setup-bun@v2
      - run: bun test
      - uses: biomejs/setup-biome@v2
      - run: biome check .
  day-04:
    name: "Day 4"
    runs-on: ubuntu-latest
    defaults: { run: { working-directory: day-04 } }
    steps:
      - uses: actions/checkout@v4
      - uses: extractions/setup-just@v2
      - run: just test
  day-05:
    name: "Day 5"
    runs-on: ubuntu-latest
    defaults: { run: { working-directory: day-05 } }
    steps:
      - uses: actions/checkout@v4
      - uses: extractions/setup-just@v2
      - uses: erlef/setup-beam@v1
        with:
          otp-version: "27.1.2"
          gleam-version: "1.6.2"
          rebar3-version: "3"
      - run: just test
  day-06:
    name: "Day 6"
    runs-on: ubuntu-latest
    defaults: { run: { working-directory: day-06 } }
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version: "1.23"
          cache-dependency-path: day-06/go.sum
      - run: go test ./...
  day-07:
    name: "Day 7"
    runs-on: ubuntu-latest
    defaults: { run: { working-directory: day-07 } }
    steps:
      - uses: actions/checkout@v4
      - uses: erlef/setup-beam@v1
        with:
          otp-version: "27.1.2"
          elixir-version: "1.17.3"
          rebar3-version: "3"
      - run: mix test  
  day-08:
    name: "Day 8"
    runs-on: ubuntu-latest
    defaults: { run: { working-directory: day-08 } }
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@stable
        with:
          toolchain: stable
          components: clippy,rustfmt
      - run: cargo test
      - run: cargo fmt
      - run: cargo clippy
  day-09:
    name: "Day 9"
    runs-on: ubuntu-latest
    defaults: { run: { working-directory: day-09 } }
    steps:
      - uses: actions/checkout@v4
      - uses: crystal-lang/install-crystal@v1
      - run: crystal spec
  day-10:
    name: "Day 10"
    runs-on: ubuntu-latest
    defaults: { run: { working-directory: day-10 } }
    steps:
      - uses: actions/checkout@v4
      - uses: jiro4989/setup-nim-action@v2
      - run: nim r main.nim test
  day-11:
    name: "Day 11"
    runs-on: ubuntu-latest
    defaults: { run: { working-directory: day-11 } }
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@
      - run: python3 day11.py test
